### ISSUE TITLE
Error when running 'make server.install'

### ISSUE THREAD

**Issue by mcoirad-gmmb** [antkahn/flask-api-starter-kit#12]
When running the above command I get the following error:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'

Does the file need to be added to the Docker image before this command can be run?

**Comment by antkahn** [comment]
Hello!

You shouldn't have to add anything to the Docker image, it should already be in your volumes.
On what OS are you running this, and what are your docker/docker-compose versions?
