### ISSUE TITLE
make db/upgrade command Error

### ISSUE THREAD

**Issue by romaduck** [antkahn/flask-api-starter-kit#6]
I can't run `make db/upgrade` command because of an Error:
`  File "src/manage.py", line 3, in <module>
    from flask_migrate import Migrate, MigrateCommand
  File "/mnt/vendor/lib/python3.4/site-packages/flask_migrate/__init__.py", line 3, in <module>
    from flask.ext.script import Manager
ImportError: No module named 'flask.ext'
make: *** [Makefile:31: db/upgrade] Error 1
`
OS - Linux Manjaro, python 3.4. 
All required packages are installed correctly, what I have to do?

**Comment by antkahn** [comment]
Hello Roman,

My bad, when I migrated to Flask v1, I forgot to update Flask-Migrate.
This should now be fixed !
